"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 11:45:57.788732
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# frozen copy of app.models.IMMUTABILITY_SQL at the time of this revision
IMMUTABILITY_SQL = ["\n    CREATE OR REPLACE FUNCTION hsa_forbid_change() RETURNS trigger AS $$\n    BEGIN\n      RAISE EXCEPTION '% on % is not allowed: rows are immutable', TG_OP, TG_TABLE_NAME;\n    END; $$ LANGUAGE plpgsql;\n    ", 'CREATE TRIGGER trg_question_version_immutable BEFORE UPDATE OR DELETE ON question_version FOR EACH ROW EXECUTE FUNCTION hsa_forbid_change();', "\n    CREATE OR REPLACE FUNCTION hsa_freeze_submitted_session() RETURNS trigger AS $$\n    BEGIN\n      IF OLD.status = 'submitted' THEN\n        RAISE EXCEPTION 'exam session % is submitted and frozen', OLD.id;\n      END IF;\n      RETURN NEW;\n    END; $$ LANGUAGE plpgsql;\n    ", 'CREATE TRIGGER trg_session_frozen BEFORE UPDATE OR DELETE ON exam_session FOR EACH ROW EXECUTE FUNCTION hsa_freeze_submitted_session();', "\n    CREATE OR REPLACE FUNCTION hsa_freeze_submitted_item() RETURNS trigger AS $$\n    DECLARE st text;\n    BEGIN\n      SELECT status INTO st FROM exam_session WHERE id = OLD.session_id;\n      IF st = 'submitted' THEN\n        RAISE EXCEPTION 'items of submitted exam session % are frozen', OLD.session_id;\n      END IF;\n      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;\n      IF NEW.question_version_id <> OLD.question_version_id OR NEW.position <> OLD.position\n         OR NEW.option_order IS DISTINCT FROM OLD.option_order THEN\n        RAISE EXCEPTION 'exam item composition is immutable';\n      END IF;\n      RETURN NEW;\n    END; $$ LANGUAGE plpgsql;\n    ", 'CREATE TRIGGER trg_item_frozen BEFORE UPDATE OR DELETE ON exam_item FOR EACH ROW EXECUTE FUNCTION hsa_freeze_submitted_item();']

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role in ('student','admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('asset',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ext', sa.String(length=8), nullable=False),
    sa.Column('mime', sa.String(length=40), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source_ref', sa.String(length=80), nullable=True),
    sa.Column('derived_from', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('exam_blueprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('price_vnd', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_vnd >= 0', name='ck_bp_price'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_vnd', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('blueprint_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts is null or attempts > 0', name='ck_product_attempts'),
    sa.CheckConstraint('price_vnd > 0', name='ck_product_price'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rate_limit',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    op.create_table('subject',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('practice_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('auth_session',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_session_user_id'), 'auth_session', ['user_id'], unique=False)
    op.create_table('password_reset',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_user_id'), 'password_reset', ['user_id'], unique=False)
    op.create_table('payment_order',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('blueprint_id', sa.Integer(), nullable=True),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount_vnd', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_amount_vnd', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("status in ('pending','paid','expired','cancelled','refunded')", name='ck_order_status'),
    sa.CheckConstraint('amount_vnd > 0', name='ck_order_amount'),
    sa.ForeignKeyConstraint(['blueprint_id'], ['exam_blueprint.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_payment_order_user_id'), 'payment_order', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('current_version_id', sa.BigInteger(), nullable=True),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('subject_code', sa.String(length=40), nullable=True),
    sa.Column('source_subject', sa.String(length=80), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('subtopic', sa.String(length=200), nullable=True),
    sa.Column('cognitive_level', sa.String(length=8), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('group_key', sa.String(length=80), nullable=True),
    sa.Column('exam_systems', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('has_formula', sa.Boolean(), nullable=False),
    sa.Column('has_table', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('review_flags', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('answer_source_type', sa.String(length=40), nullable=True),
    sa.Column('editorial_state', sa.String(length=40), nullable=False),
    sa.Column('editorial_states', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('state_source', sa.String(length=24), nullable=False),
    sa.Column('state_notes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('scoring_mode', sa.String(length=16), nullable=False),
    sa.Column('answer_kind', sa.String(length=16), nullable=True),
    sa.Column('content_flags', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('policy_eligible', sa.Boolean(), nullable=False),
    sa.Column('policy_reasons', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('admin_override', sa.String(length=16), nullable=True),
    sa.Column('admin_override_note', sa.Text(), nullable=True),
    sa.Column('admin_override_by', sa.BigInteger(), nullable=True),
    sa.Column('admin_override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_served', sa.Boolean(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('removed_upstream', sa.Boolean(), nullable=False),
    sa.Column('first_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("admin_override is null or admin_override in ('enable','disable')", name='ck_q_override'),
    sa.CheckConstraint("scoring_mode in ('auto','self_check','none')", name='ck_q_scoring_mode'),
    sa.ForeignKeyConstraint(['admin_override_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['question_version.id'], name='fk_question_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'external_id', name='uq_question_bank_external')
    )
    op.create_index('ix_question_group', 'question', ['group_key'], unique=False)
    op.create_index('ix_question_pool', 'question', ['is_served', 'subject_code', 'question_type'], unique=False)
    op.create_index('ix_question_state', 'question', ['editorial_state'], unique=False)
    op.create_table('subject_alias',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('source_value', sa.String(length=80), nullable=False),
    sa.Column('subject_code', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.code'], ),
    sa.PrimaryKeyConstraint('bank_id', 'source_value')
    )
    op.create_table('sync_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=200), nullable=True),
    sa.Column('checkpoint', sa.String(length=80), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entitlement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('blueprint_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('attempts_total', sa.Integer(), nullable=True),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts_total is null or attempts_used <= attempts_total', name='ck_ent_attempts'),
    sa.ForeignKeyConstraint(['granted_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['payment_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_entitlement_user_id'), 'entitlement', ['user_id'], unique=False)
    op.create_table('payment_transaction',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('provider_txn_id', sa.String(length=120), nullable=False),
    sa.Column('amount_vnd', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['payment_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_txn_id', name='uq_txn_provider_id')
    )
    op.create_index(op.f('ix_payment_transaction_order_id'), 'payment_transaction', ['order_id'], unique=False)
    op.create_table('question_version',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_revision', sa.String(length=120), nullable=True),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'content_hash', name='uq_version_hash'),
    sa.UniqueConstraint('question_id', 'version_no', name='uq_version_no')
    )
    op.create_index(op.f('ix_question_version_question_id'), 'question_version', ['question_id'], unique=False)
    op.create_table('bookmark',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('question_version_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_version.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_table('entitlement_usage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entitlement_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['exam_blueprint.id'], ),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_entitlement_usage_entitlement_id'), 'entitlement_usage', ['entitlement_id'], unique=False)
    op.create_table('exam_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=True),
    sa.Column('blueprint_version', sa.Integer(), nullable=True),
    sa.Column('blueprint_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seed', sa.String(length=64), nullable=False),
    sa.Column('generator_version', sa.String(length=20), nullable=False),
    sa.Column('pool_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('feedback', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_section', sa.Integer(), nullable=False),
    sa.Column('section_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submit_reason', sa.String(length=16), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entitlement_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status in ('in_progress','submitted','abandoned')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['blueprint_id'], ['exam_blueprint.id'], ),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_session_user_id'), 'exam_session', ['user_id'], unique=False)
    op.create_index('ix_session_user_status', 'exam_session', ['user_id', 'status'], unique=False)
    op.create_table('question_report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('question_version_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category in ('wrong_answer','broken_formula','broken_image','typo','unclear','other')", name='ck_report_category'),
    sa.CheckConstraint("status in ('open','triaged','resolved','rejected')", name='ck_report_status'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_version.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_report_question_id'), 'question_report', ['question_id'], unique=False)
    op.create_table('exam_item',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('question_version_id', sa.BigInteger(), nullable=False),
    sa.Column('option_order', postgresql.ARRAY(sa.String(length=2)), nullable=True),
    sa.Column('group_key', sa.String(length=80), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('scoring_mode', sa.String(length=16), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('self_assessment', sa.String(length=12), nullable=True),
    sa.Column('outcome', sa.String(length=12), nullable=True),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_version.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'position')
    )
    op.create_index(op.f('ix_exam_item_question_id'), 'exam_item', ['question_id'], unique=False)
    op.create_table('question_correction',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['question_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_correction_question_id'), 'question_correction', ['question_id'], unique=False)
    # ### end Alembic commands ###
    for stmt in IMMUTABILITY_SQL:
        op.execute(stmt)


def downgrade():
    op.execute('DROP TRIGGER IF EXISTS trg_question_version_immutable ON question_version')
    op.execute('DROP TRIGGER IF EXISTS trg_session_frozen ON exam_session')
    op.execute('DROP TRIGGER IF EXISTS trg_item_frozen ON exam_item')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_correction_question_id'), table_name='question_correction')
    op.drop_table('question_correction')
    op.drop_index(op.f('ix_exam_item_question_id'), table_name='exam_item')
    op.drop_table('exam_item')
    op.drop_index(op.f('ix_question_report_question_id'), table_name='question_report')
    op.drop_table('question_report')
    op.drop_index('ix_session_user_status', table_name='exam_session')
    op.drop_index(op.f('ix_exam_session_user_id'), table_name='exam_session')
    op.drop_table('exam_session')
    op.drop_index(op.f('ix_entitlement_usage_entitlement_id'), table_name='entitlement_usage')
    op.drop_table('entitlement_usage')
    op.drop_table('bookmark')
    op.drop_index(op.f('ix_question_version_question_id'), table_name='question_version')
    op.drop_table('question_version')
    op.drop_index(op.f('ix_payment_transaction_order_id'), table_name='payment_transaction')
    op.drop_table('payment_transaction')
    op.drop_index(op.f('ix_entitlement_user_id'), table_name='entitlement')
    op.drop_table('entitlement')
    op.drop_table('sync_run')
    op.drop_table('subject_alias')
    op.drop_index('ix_question_state', table_name='question')
    op.drop_index('ix_question_pool', table_name='question')
    op.drop_index('ix_question_group', table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_payment_order_user_id'), table_name='payment_order')
    op.drop_table('payment_order')
    op.drop_index(op.f('ix_password_reset_user_id'), table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_index(op.f('ix_auth_session_user_id'), table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_setting')
    op.drop_table('subject')
    op.drop_table('rate_limit')
    op.drop_table('question_bank')
    op.drop_table('product')
    op.drop_table('exam_blueprint')
    op.drop_table('asset')
    op.drop_table('app_user')
    # ### end Alembic commands ###
