"""subject inference, bank metadata, source documents, formula checks

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 18:26:52.598417
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula_check',
    sa.Column('tex_sha', sa.String(length=64), nullable=False),
    sa.Column('tex', sa.Text(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('renderer', sa.String(length=40), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tex_sha')
    )
    op.create_table('source_document',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'external_id', name='uq_source_document')
    )
    op.add_column('question', sa.Column('inferred_subject', sa.String(length=80), nullable=True))
    op.add_column('question', sa.Column('inference_confidence', sa.String(length=16), nullable=True))
    op.add_column('question', sa.Column('inference_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('question', sa.Column('subject_override', sa.String(length=40), nullable=True))
    op.add_column('question', sa.Column('subject_override_note', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('subject_source', sa.String(length=16), server_default='original', nullable=False))
    op.create_foreign_key('fk_question_subject_override', 'question', 'subject', ['subject_override'], ['code'])
    # 0001 declared this FK with use_alter inside create_table, which Alembic does not emit: add it now
    op.create_foreign_key('fk_question_current_version', 'question', 'question_version', ['current_version_id'], ['id'])
    op.add_column('question_bank', sa.Column('version', sa.String(length=80), nullable=True))
    op.add_column('question_bank', sa.Column('source_uri', sa.Text(), nullable=True))
    op.add_column('question_bank', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('question_bank', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE question SET subject_source = 'unclassified' WHERE subject_code IS NULL OR subject_code = 'general'")
    op.create_index('ix_question_inferred_subject', 'question', ['inferred_subject'])


def downgrade():
    op.drop_index('ix_question_inferred_subject', table_name='question')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_bank', 'last_synced_at')
    op.drop_column('question_bank', 'settings')
    op.drop_column('question_bank', 'source_uri')
    op.drop_column('question_bank', 'version')
    op.drop_constraint('fk_question_current_version', 'question', type_='foreignkey')
    op.drop_constraint('fk_question_subject_override', 'question', type_='foreignkey')
    op.drop_column('question', 'subject_source')
    op.drop_column('question', 'subject_override_note')
    op.drop_column('question', 'subject_override')
    op.drop_column('question', 'inference_evidence')
    op.drop_column('question', 'inference_confidence')
    op.drop_column('question', 'inferred_subject')
    op.drop_table('source_document')
    op.drop_table('formula_check')
    # ### end Alembic commands ###
