"""upstream effective subject classification

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 21:45:37.436247
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('upstream_effective_subject', sa.String(length=80), nullable=True))
    op.add_column('question', sa.Column('classification_source', sa.String(length=40), nullable=True))
    op.add_column('question', sa.Column('classification_confidence', sa.String(length=16), nullable=True))
    op.add_column('question', sa.Column('classification_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('question', sa.Column('classification_review', sa.String(length=60), nullable=True))
    op.alter_column('question', 'subject_source',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'original'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # values introduced by this revision do not fit the old column width
    op.execute("UPDATE question SET subject_source = 'original' WHERE subject_source = 'upstream_effective'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'subject_source',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'original'::character varying"))
    op.drop_column('question', 'classification_review')
    op.drop_column('question', 'classification_evidence')
    op.drop_column('question', 'classification_confidence')
    op.drop_column('question', 'classification_source')
    op.drop_column('question', 'upstream_effective_subject')
    # ### end Alembic commands ###
